name: Build IPA

on:
  push:
    branches:
      - main  # Trigger build on main branch. Modify if needed.

jobs:
  build-ipa:
    runs-on: macos-12  # Ensures compatibility with macOS runners

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: actions/setup-flutter@v2
        with:
          flutter-version: '3.10.5'  # Use a specific Flutter version here

      - name: Switch to stable channel
        run: flutter channel stable && flutter upgrade

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS app
        env:
          CI: true
        run: flutter build ipa --release --export-options-plist=ExportOptions.plist

      - name: Upload IPA to GitHub Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: MyApp.ipa
          path: build/ios/ipa/*.ipa
